#들여쓰기 매우 중요
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  #한글 깨짐 오류 해결 방안
  sql:
    init:
      mode: always
      encoding: UTF-8
